### PR TITLE
Death/Necropsy form updates, and 'performedby' related various fixes

### LINKED ISSUE #307: [NIRC] Basic colony management - Death form updates
### Tasks
- [x] Filter 'Submit for Review' drop down to filter on Vets
- [x] Error handling/interim QC State
- [x] 'Performed By' values - data entry workflow
- [x] Allow past dates and allow time component
- [x] Navigation for Vets to get to Death/Necropsy form
- [x] Fix broken lookups for 'performed by' in various reports
- [x] Code review @labkey-martyp @ankurjuneja 
- [x] Code review changes
- [x] Test fixes
- [x] TC verify and merge

### PR DESCRIPTION
**Pull request by labkey-bpatel**
#### Rationale
The Death/Necropsy workflow needed a little fine tuning to align with the real world workflow.
Also, reported broken 'performedBy' lookups various reports.

#### Related Pull Requests
* 

#### Changes
* Filter 'Submit for Review' drop down to filter on Vets.
* Set QC state to 'Request Pending' when Death is submitted and update the triggers.
* Allow request in the past and add time component.
* Add link to necropsy tasks for the vets on the main page.
* Various 'performedby' related fixes : save userId instead of displayName, update lookup to use userId as keyfield instead of displayName,  'performed by' value not getting displayed in a data entry form panel.
* Update necropsyTasks.sql to further clarify qc state of 'Request: Pending' and 'Review Required', and update metadata to format the background color on the values.
* Remove 'project' from metadata, upgrade script to reloadFolder, update schema version.
* Use DbScope.CommitTaskOption.POSTCOMMIT when sending Death Notification.
* Add Gross Pathology and Tissue Disposition to the Reports.
* Update 'Submit Death' handler not to create Necropsy, Gross Pathology, and Tissue Disposition empty records when submitting a Death record.
* Update 'Submit for Review' button text to 'Submit Necropsy for Review' for clarity.
* Test fix - Make "Submit for Review" a little more reliable.

### CODE REVIEW

File: nirc_ehr/resources/queries/ehr/necropsyTasks.sql [hunk 1]
```diff
@@ -0,0 +1,10 @@
+SELECT
+    taskid,
+    updateTitle AS form,
+    assignedTo,
+    created,
+    createdBy,
+    modified,
+    modifiedBy,
+    qcstate
```
Comment (labkey-martyp) [inline nirc_ehr/resources/queries/ehr/necropsyTasks.sql]: Since we're re-purposing qcstates here a little, can you also create a new column here containing a new string that translates the qcstates. Mapping qcstates to something like "Request: Pending" -> "Death Entered: Necropsy Pending" and "Review Required" -> "Necropsy Entered: Review Required".

Then in the .query.xml make these two states yellow like the qcstate. And in the default view show these two columns instead of qcstate.

File: nirc_ehr/resources/queries/study/deaths.js [hunk 2]
```diff
@@ -62,11 +78,22 @@ function onUpsert(helper, scriptErrors, row, oldRow) {
...
             // check if the animal is at the center
             if (idMap[row.Id].calculated_status.toUpperCase() === 'SHIPPED') {
                 EHR.Server.Utils.addError(scriptErrors, 'Id', 'Animal is not at the center.', 'ERROR');
             }
 
+            // check if the animal is pending review on Death record
+            // Note: Upon 'Submit Death', the QCState will get set to 'REQUEST: PENDING', and upon 'Submit for Review',
+            // the QCState will get set to 'Review Required' - this way we can distinguish between the two states in the Death/Necropsy workflow. And if the user
+            // tries to submit a Death record for an animal that already exists with one of these two QCStates, below error message will be displayed.
+            if (row.QCStateLabel.toUpperCase() === 'IN PROGRESS' &&
```
Comment (labkey-martyp) [inline nirc_ehr/resources/queries/study/deaths.js]: I'm not totally following why IN PROGRESS is being used here. Can you walk me through that?

File: nirc_ehr/resources/queries/study/deaths.query.xml [hunk 3]
```diff
@@ -18,10 +18,23 @@
...
-                    <column columnName="performedby"/>
+                    <column columnName="performedby">
+                        <fk>
+                            <fkDbSchema>core</fkDbSchema>
+                            <fkTable>Users</fkTable>
+                            <fkColumnName>UserId</fkColumnName>
+                            <fkDisplayColumnName>DisplayName</fkDisplayColumnName>
+                        </fk>
+                    </column>
                     <column columnName="project">
```
Comment (labkey-martyp) [inline nirc_ehr/resources/queries/study/deaths.query.xml]: We shouldn't be using project in any of these datasets. If they're in the datset we should remove it. The project is what the animal is assigned to.

File: nirc_ehr/resources/queries/study/grossPathology.query.xml [hunk 4]
```diff
@@ -19,6 +19,21 @@
                             <fkColumnName>value</fkColumnName>
                         </fk>
                     </column>
+                    <column columnName="performedby">
+                        <isHidden>true</isHidden>
+                    </column>
+                    <column columnName="project">
```
Comment (labkey-martyp) [inline nirc_ehr/resources/queries/study/grossPathology.query.xml:25]: Same here about project.

**Review by labkey-martyp — APPROVED** [review]
Overall looks good. A few inline comments. Can you also update animal history reports under pathology.

File: nirc_ehr/resources/queries/study/deaths.js (hunk 2 above)
Comment (labkey-bpatel) [reply nirc_ehr/resources/queries/study/deaths.js]: Comment updated.

File: nirc_ehr/resources/queries/ehr/necropsyTasks.sql (hunk 1 above)
Comment (labkey-bpatel) [reply nirc_ehr/resources/queries/ehr/necropsyTasks.sql]: Done!

File: nirc_ehr/resources/queries/study/deaths.query.xml (hunk 3 above)
Comment (labkey-bpatel) [reply nirc_ehr/resources/queries/study/deaths.query.xml]: Project removed with required updates

File: nirc_ehr/resources/queries/study/grossPathology.query.xml (hunk 4 above)
Comment (labkey-bpatel) [reply nirc_ehr/resources/queries/study/grossPathology.query.xml:25]: done

File: nirc_ehr/resources/queries/study/deaths/.qview.xml [hunk 5]
```diff
@@ -0,0 +1,12 @@
+<customView xmlns="http://labkey.org/data/xml/queryCustomView">
+<!--    <sorts>-->
+<!--        <sort column="date" descending="true"/>-->
+<!--    </sorts>-->
```
Comment (labkey-martyp) [inline nirc_ehr/resources/queries/study/deaths/.qview.xml]: Uncomment?

**Review by labkey-martyp — APPROVED** [review]
Looks great. Can you please take on more pass at the animal history pathology reports. Some of the column names are capitalized and some not. Please just update the column titles in the respective .query.xml files.
